from typing import Any, Callable, Tuple
from types import TracebackType

class Button:
    left: Any
    right: Any
    middle: Any

class Controller:
    position: Any
    def move(self, x: float, y: float) -> None: ...
    def click(self, button: Button, count: int = ...) -> None: ...
    def press(self, button: Button) -> None: ...
    def release(self, button: Button) -> None: ...
    def scroll(self, dx: float, dy: float) -> None: ...

class Listener:
    def __init__(
        self,
        on_move: Callable[[float, float], Any] | None = ...,
        on_click: Callable[[float, float, Button, bool], Any] | None = ...,
        on_scroll: Callable[[float, float, float, float], Any] | None = ...,
        suppress: bool | None = ...,
    ) -> None: ...
    daemon: bool
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def join(self) -> None: ...
    def __enter__(self) -> "Listener": ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
